import { querySnowflake } from "@/lib/snowflake"
export const dynamic = "force-dynamic"

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url)
  const claimId = searchParams.get("claimId")

  if (!claimId) {
    return new Response("Missing claimId", { status: 400 })
  }

  try {
    const safe = claimId.replace(/'/g, "''")
    const rows = await querySnowflake(`
      SELECT c.CLAIM_ID, c.CUSTOMER_NAME, c.CLAIM_TYPE, c.CLAIM_DATE,
             c.CLAIM_AMOUNT, c.STATUS, c.DESCRIPTION, c.RESOLUTION_DATE, c.COUNTRY,
             g.EMAIL AS CUSTOMER_EMAIL
      FROM ANDE_DB.PUBLIC.CUSTOMER_CLAIMS c
      LEFT JOIN ANDE_DB.PUBLIC.CUSTOMER_MASTER_GOLDEN_TABLE g
        ON c.MASTER_CUSTOMER_ID = g.MASTER_CUSTOMER_ID
      WHERE c.CLAIM_ID = '${safe}'
      LIMIT 1
    `)

    if (!rows || rows.length === 0) {
      return new Response("Claim not found", { status: 404 })
    }

    const claim = rows[0] as Record<string, string | number>
    const pdf = generateClaimPDF(claim)

    return new Response(pdf, {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename=${claimId.replace(/[^a-zA-Z0-9-]/g, "_")}_Report.pdf`,
      },
    })
  } catch (e) {
    console.error("[documents/pdf]", e)
    return new Response("Failed to generate PDF", { status: 500 })
  }
}

function generateClaimPDF(claim: Record<string, string | number>): Buffer {
  const pageWidth = 595
  const pageHeight = 842
  const margin = 50
  const lineHeight = 16

  let currentY = pageHeight - margin
  let stream = ""

  function addText(text: string, x: number, fontSize: number, bold = false) {
    const font = bold ? "/F2" : "/F1"
    stream += `BT\n${font} ${fontSize} Tf\n${x} ${currentY} Td\n(${escapePdf(text)}) Tj\nET\n`
  }

  function addLine() {
    stream += `${margin} ${currentY - 2} m ${pageWidth - margin} ${currentY - 2} l S\n`
    currentY -= lineHeight
  }

  function newLine(count = 1) {
    currentY -= lineHeight * count
  }

  // Title
  addText("Insurance Claim Report", margin, 18, true)
  newLine(2)

  addText(`Claim ID: ${claim.CLAIM_ID}`, margin, 11, true)
  newLine()
  addText(`Generated: ${new Date().toISOString().split("T")[0]}`, margin, 9)
  newLine(1.5)
  addLine()
  newLine()

  // Claim details
  addText("CLAIM DETAILS", margin, 12, true)
  newLine(1.5)

  const fields = [
    ["Claim ID", String(claim.CLAIM_ID)],
    ["Customer", String(claim.CUSTOMER_NAME)],
    ["Email", String(claim.CUSTOMER_EMAIL || "N/A")],
    ["Claim Type", String(claim.CLAIM_TYPE)],
    ["Date Filed", String(claim.CLAIM_DATE)],
    ["Amount", `EUR ${Number(claim.CLAIM_AMOUNT).toLocaleString()}`],
    ["Status", String(claim.STATUS)],
    ["Country", String(claim.COUNTRY)],
    ["Resolution Date", String(claim.RESOLUTION_DATE || "Pending")],
  ]

  for (const [label, value] of fields) {
    addText(`${label}:`, margin, 10, true)
    addText(value, margin + 120, 10)
    newLine()
  }

  newLine()
  addLine()
  newLine()

  // Description
  addText("DESCRIPTION", margin, 12, true)
  newLine(1.5)

  const desc = String(claim.DESCRIPTION || "No description available.")
  const words = desc.split(" ")
  let line = ""
  const maxChars = 80

  for (const word of words) {
    if ((line + " " + word).length > maxChars) {
      addText(line.trim(), margin, 10)
      newLine()
      line = word
    } else {
      line += " " + word
    }
  }
  if (line.trim()) {
    addText(line.trim(), margin, 10)
    newLine()
  }

  newLine(2)
  addLine()
  newLine()
  addText("This document is generated by AND.e Insurance Services Ltd.", margin, 8)
  newLine()
  addText("Underwriter: AND.e Underwriting DAC.", margin, 8)

  // Build PDF structure
  return buildPdf(stream, pageWidth, pageHeight)
}

function buildPdf(contentStream: string, pageWidth: number, pageHeight: number): Buffer {
  let pdf = "%PDF-1.4\n"
  const offsets: number[] = []
  let objNum = 1

  function addObj(content: string): number {
    offsets.push(pdf.length)
    pdf += `${objNum} 0 obj\n${content}\nendobj\n`
    return objNum++
  }

  addObj("<< /Type /Catalog /Pages 2 0 R >>")
  const streamBytes = Buffer.from(contentStream, "latin1")
  addObj(`<< /Type /Pages /Kids [5 0 R] /Count 1 >>`)
  const f1 = addObj("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>")
  const f2 = addObj("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>")
  addObj(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${pageWidth} ${pageHeight}] /Contents 6 0 R /Resources << /Font << /F1 ${f1} 0 R /F2 ${f2} 0 R >> >> >>`)
  addObj(`<< /Length ${streamBytes.length} >>\nstream\n${contentStream}\nendstream`)

  const xrefOffset = pdf.length
  pdf += "xref\n"
  pdf += `0 ${objNum}\n`
  pdf += "0000000000 65535 f \n"
  for (const off of offsets) {
    pdf += `${String(off).padStart(10, "0")} 00000 n \n`
  }
  pdf += "trailer\n"
  pdf += `<< /Size ${objNum} /Root 1 0 R >>\n`
  pdf += "startxref\n"
  pdf += `${xrefOffset}\n`
  pdf += "%%EOF\n"

  return Buffer.from(pdf, "latin1")
}

function escapePdf(str: string): string {
  return (str || "").replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)")
}
